export const Executives = [
  {
    title: "Avni Kapoor",
    img: "Avni.jpg",
    linkedin: "https://www.linkedin.com/in/avni-kapoor/",
    position: "Co-president",
    lastPosition: "",
  },
  {
    title: "Hinako Kamiya",
    img: "Hinako.jpg",
    linkedin: "https://www.linkedin.com/in/hinako-kamiya/",
    position: "Co-president",
    lastPosition: "",
  },

  {
    title: "Melvika Faustine",
    img: "Melvika.jpg",
    linkedin: "https://www.linkedin.com/in/melvika/",
    position: "VP Internal",
    lastPosition: "",
  },
  {
    title: "Terry Kwok",
    img: "Terry.jpg",
    linkedin: "https://www.linkedin.com/in/lai-chit-kwok-6074472b5/",
    position: "VP Internal",
    lastPosition: "",
  },
  {
    title: "Ananya Singh",
    img: "AnanyaSingh.jpg",
    linkedin: "https://www.linkedin.com/in/ananyaxsingh/",
    position: "Co-President",
    lastPosition: "",
  },
  {
    title: "Nicolas Ramirez",
    img: "NicolasRamirez.jpg",
    linkedin: "https://www.linkedin.com/in/nicolas-ramirez-pm/",
    position: "VP Product",
    lastPosition: "",
  },
  {
    title: "Caron McPherson",
    img: "Caron.png",
    linkedin:
      "https://www.linkedin.com/in/caron-isaiah-mcpherson-71b562278/",
    position: "VP Marketing",
    lastPosition: "",
  },
  {
    title: "Kate Simone",
    img: "Kate.jpg",
    linkedin: "https://www.linkedin.com/in/kate-simone-866335284/",
    position: "VP Design",
    lastPosition: "",
  },
  {
    title: "Sylvia Zhang",
    img: "Sylvia.jpg",
    linkedin: "https://www.linkedin.com/in/sylvia-zhang-siqi/",
    position: "VP Scoping",
    lastPosition: "",
  },
  {
    title: "Irvin Cardoza",
    img: "IrvinCardoza.jpg",
    linkedin: "https://www.linkedin.com/in/irvincardoza/",
    position: "VP Scoping",
    lastPosition: "",
  },
    {
    title: "Bidisha Roy",
    img: "BidishaRoy.jpg",
    linkedin: "https://www.linkedin.com/in/bidisha--roy/",
    role: "VP Internal",
    roleType: ["exec"],
    lastPosition: "",
  },
  {
    title: "Lavanya Sharma",
    img: "LavanyaSharma.jpeg",
    linkedin: "",
    role: "VP Marketing",
    roleType: ["exec"],
    lastPosition: "",
  }
];